version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
  steamapp:
    build:
      dockerfile: Dockerfile.dev
      context: ./steamapp
    volumes:
      - /app/node_modules
      - ./steamapp:/app
    stdin_open: true
    ports:
      - '3000:3000'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - PGTABLE=steamfriends
      - STEAMKEY=D0BE124A87EC59ACF0409F455B01B549
    ports:
      - '3001:3001'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - PGTABLE=steamfriends
      - STEAMKEY=D0BE124A87EC59ACF0409F455B01B549