apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: alexanders1337/server
          env:
            - name: REDIS_HOST
              value: redis-clusterip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-clusterip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGPORT
              value: '5432'
            - name: PGTABLE
              value: steamfriends
            - name: STEAMKEY
              valueFrom: 
                secretKeyRef:
                  name: steamapikey
                  key: STEAMKEY
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 3001
      targetPort: 3001