apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistentvolume-claim
spec:
  storageClassName: gold
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 2Gi